services:
  app:
    container_name: todocamisetas_examen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_KEY: base64:3pF8dZqfG0WJp7l7w7qg1mZPq9mKf8t4xD0V1n8m6xg=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todocamisetas
      DB_USERNAME: todocamisetasuser
      DB_PASSWORD: todocamisetaspass
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    container_name: todocamisetas_examen-db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: todocamisetas
      MYSQL_USER: todocamisetasuser
      MYSQL_PASSWORD: todocamisetaspass
      MYSQL_ROOT_PASSWORD: rootpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -prootpass --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-data:
